<!doctype html>
<!-- Made in Framer · framer.com ✨ -->
<!-- Published Dec 10, 2025, 2:58 PM UTC -->
<html lang="en">
<head>
    <meta charset="utf-8">
    
    
    <script>try{if(localStorage.get("__framer_force_showing_editorbar_since")){const n=document.createElement("link");n.rel = "modulepreload";n.href="https://framer.com/edit/init.mjs";document.head.appendChild(n)}}catch(e){}</script>
    <!-- Start of headStart -->
    
    <!-- End of headStart -->
    <meta name="viewport" content="width=device-width">
    <meta name="generator" content="Framer 0b89d47">
    <title>UIUXfolio | Professional UI/UX Designer Portfolio</title>
    <meta name="description" content="Explore the portfolio of a professional UI/UX designer showcasing full case studies. Each project walks you through research, design decisions, prototypes, and final results, highlighting a user-centered process.">
    <meta name="framer-search-index" content="https://framerusercontent.com/sites/6lbWNZykUzbfD1tnNOprHt/searchIndex-vcadRXLFguL7.json">
    <meta name="framer-search-index-fallback" content="https://framerusercontent.com/sites/6lbWNZykUzbfD1tnNOprHt/searchIndex-dW3jhcoNVuzB.json">
    <link href="https://framerusercontent.com/images/onj9NIHcs7C6WzDMbi9icig7zBE.png" rel="icon" media="(prefers-color-scheme: light)">
    <link href="https://framerusercontent.com/images/onj9NIHcs7C6WzDMbi9icig7zBE.png" rel="icon" media="(prefers-color-scheme: dark)">
    <link rel="apple-touch-icon" href="https://framerusercontent.com/images/4RgveUELP3wqhMv3LHEJRQ2Kqm0.png">
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="UIUXfolio | Professional UI/UX Designer Portfolio">
    <meta property="og:description" content="Explore the portfolio of a professional UI/UX designer showcasing full case studies. Each project walks you through research, design decisions, prototypes, and final results, highlighting a user-centered process.">
    <meta property="og:image" content="https://framerusercontent.com/images/NB5GmuJdVHDXi0y5bJgqhqXfTg.png">
    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="UIUXfolio | Professional UI/UX Designer Portfolio">
    <meta name="twitter:description" content="Explore the portfolio of a professional UI/UX designer showcasing full case studies. Each project walks you through research, design decisions, prototypes, and final results, highlighting a user-centered process.">
    <meta name="twitter:image" content="https://framerusercontent.com/images/NB5GmuJdVHDXi0y5bJgqhqXfTg.png">
